name: Swift

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3
    - name: SwiftLint Action
      uses: raphaelbussa/swiftlint-action@v1.0.0

#     - name: Build
#       run: swift build -v
#     - name: Run tests
#       run: swift test -v
